import { useState } from 'react'
import { FileText, Download, AlertCircle, Pill, Activity, Clock, FileUp, Loader2, User, Stethoscope, Mail, Send, CheckCircle } from 'lucide-react'
import { CONFIG } from '../lib/config'
import { AppPage, PageHeader, SurfaceCard, PrimaryButton, SecondaryButton, EmptyState, TextInput, SelectInput, StatusBanner, Badge, appTheme } from '../components/AppPrimitives'

function downloadPDF(brief) {
  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Doctor Brief - AarogyaVaani</title>
<style>
  body { font-family: Georgia, serif; color: #1a1a1a; max-width: 700px; margin: 0 auto; padding: 40px 30px; line-height: 1.6; }
  h1 { color: #8b6914; font-size: 24px; border-bottom: 2px solid #d4a84b; padding-bottom: 8px; margin-bottom: 4px; }
  .subtitle { color: #666; font-size: 12px; margin-bottom: 24px; }
  h2 { color: #4a3520; font-size: 16px; margin-top: 24px; border-left: 3px solid #d4a84b; padding-left: 10px; }
  .chip { display: inline-block; background: #fff3e0; color: #8b6914; padding: 2px 10px; border-radius: 12px; font-size: 12px; margin: 2px 4px 2px 0; }
  .concern { padding: 6px 0; border-bottom: 1px solid #f0ebe4; font-size: 14px; }
  .report { padding: 6px 0; border-bottom: 1px solid #f0ebe4; font-size: 13px; }
  .report-name { font-weight: bold; }
  .report-meta { color: #888; font-size: 11px; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e0d8cc; color: #999; font-size: 11px; text-align: center; }
  .summary { background: #faf6ef; padding: 14px 18px; border-radius: 8px; font-size: 14px; white-space: pre-wrap; }
  @media print { body { padding: 20px; } }
</style></head><body>
<h1>AarogyaVaani — Doctor Handoff Brief</h1>
<div class="subtitle">Patient ID: ${brief.user_id} &nbsp;|&nbsp; Generated: ${new Date(brief.generated_at).toLocaleString()} &nbsp;|&nbsp; Conversations: ${brief.conversation_count}</div>

<h2>Patient Summary</h2>
<div class="summary">${brief.summary}</div>

${brief.key_conditions.length ? `<h2>Key Conditions</h2><div>${brief.key_conditions.map((c) => `<span class="chip">${c}</span>`).join('')}</div>` : ''}

${brief.medications.length ? `<h2>Medications</h2><div>${brief.medications.map((m) => `<span class="chip">${m}</span>`).join('')}</div>` : ''}

${brief.recent_concerns.length ? `<h2>Recent Concerns</h2>${brief.recent_concerns.map((c) => `<div class="concern">• ${c}</div>`).join('')}` : ''}

${brief.uploaded_reports.length ? `<h2>Uploaded Reports</h2>${brief.uploaded_reports.map((r) => `<div class="report"><span class="report-name">${r.report_name}</span><br><span class="report-meta">${r.summary || ''} — ${r.saved_at ? new Date(r.saved_at).toLocaleDateString() : ''}</span></div>`).join('')}` : ''}

<div class="footer">Generated by AarogyaVaani AI Healthcare Assistant — For doctor reference only, not a diagnosis.<br>This document aggregates patient-reported data, uploaded reports, and AI conversation history.</div>
</body></html>`

  const w = window.open('', '_blank', 'width=800,height=900')
  w.document.write(html)
  w.document.close()
  setTimeout(() => { w.print() }, 400)
}

export default function DoctorBriefPage() {
  const [userId, setUserId] = useState('demo-user')
  const [brief, setBrief] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [language, setLanguage] = useState('en')
  const [doctorEmail, setDoctorEmail] = useState('')
  const [doctorName, setDoctorName] = useState('')
  const [clinicName, setClinicName] = useState('')
  const [emailSending, setEmailSending] = useState(false)
  const [emailSent, setEmailSent] = useState(false)
  const [emailError, setEmailError] = useState('')

  async function generate() {
    setLoading(true)
    setError('')
    setBrief(null)
    try {
      const res = await fetch(`${CONFIG.API_BASE_URL}/doctor_brief`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: userId, language }),
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const data = await res.json()
      if (data.status === 'error') throw new Error(data.error || 'Failed')
      setBrief(data)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  async function sendEmail() {
    setEmailSending(true)
    setEmailError('')
    setEmailSent(false)
    try {
      const res = await fetch(`${CONFIG.API_BASE_URL}/email_doctor_brief`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          user_id: userId,
          doctor_email: doctorEmail,
          doctor_name: doctorName || 'Doctor',
          clinic_name: clinicName,
          language,
        }),
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const data = await res.json()
      if (data.status === 'error') throw new Error(data.error || 'Failed')
      setEmailSent(true)
    } catch (err) {
      setEmailError(err.message)
    } finally {
      setEmailSending(false)
    }
  }

  return (
    <AppPage maxWidth="74rem">
      <PageHeader
        icon={Stethoscope}
        eyebrow="Doctor handoff"
        title="Generate a doctor-ready brief"
        subtitle="Pull together conversations, uploaded reports, medications, and recurring concerns into a single printable summary."
      />

      <div className="grid lg:grid-cols-[0.95fr_1.45fr] gap-4">
        <SurfaceCard title="Brief setup" icon={FileText}>
          <div style={{ display: 'grid', gap: '0.9rem' }}>
            <TextInput label="Patient ID" value={userId} onChange={(e) => setUserId(e.target.value)} placeholder="Enter patient or user ID" />
            <SelectInput label="Brief language" value={language} onChange={(e) => setLanguage(e.target.value)}>
              <option value="en">English (Clinical)</option>
              <option value="hi">Hindi</option>
              <option value="kn">Kannada</option>
            </SelectInput>
            <PrimaryButton onClick={generate} disabled={loading || !userId.trim()}>
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
              {loading ? 'Generating brief...' : 'Generate brief'}
            </PrimaryButton>
            <div style={{ fontSize: '0.84rem', lineHeight: 1.65, color: appTheme.espressoSoft }}>
              The generated brief is meant for handoff and context, not diagnosis. It references reports already stored in memory.
            </div>
          </div>
        </SurfaceCard>

        <SurfaceCard title="What gets included" icon={Activity}>
          <div className="grid sm:grid-cols-2 gap-3">
            {[
              ['Conversation summary', 'Recent calls, symptoms, and recurring concerns'],
              ['Uploaded reports', 'Saved report names, summaries, medicines, and conditions'],
              ['Medication context', 'Medicines mentioned across documents and conversations'],
              ['Clinical handoff', 'Doctor-friendly structure for faster review'],
            ].map(([title, detail]) => (
              <div key={title} style={{ padding: '0.95rem', borderRadius: '1rem', background: 'rgba(34,22,14,0.03)', border: `1px solid ${appTheme.border}` }}>
                <div style={{ fontSize: '0.92rem', fontWeight: 700, color: appTheme.espresso }}>{title}</div>
                <div style={{ fontSize: '0.82rem', lineHeight: 1.6, color: appTheme.espressoSoft, marginTop: '0.25rem' }}>{detail}</div>
              </div>
            ))}
          </div>
        </SurfaceCard>
      </div>

      {error ? <div style={{ marginTop: '1rem' }}><StatusBanner icon={AlertCircle} title="Could not generate brief" subtitle={error} tone="danger" /></div> : null}

      {brief ? (
        <div style={{ marginTop: '1rem', display: 'grid', gap: '1rem' }}>
          <StatusBanner
            icon={Stethoscope}
            title={`Brief generated from ${brief.conversation_count} conversation${brief.conversation_count === 1 ? '' : 's'}`}
            subtitle="Download or print a doctor-ready summary with recent context and uploaded reports."
            tone="success"
            actions={<PrimaryButton onClick={() => downloadPDF(brief)}><Download className="w-4 h-4" />Download PDF</PrimaryButton>}
          />

          <SurfaceCard title="Email to doctor's clinic" icon={Mail}>
            <div style={{ display: 'grid', gap: '0.9rem' }}>
              <p style={{ fontSize: '0.84rem', lineHeight: 1.65, color: appTheme.espressoSoft, margin: 0 }}>
                Send this patient summary directly to the doctor's clinic email so they have full context before or after a visit.
              </p>
              <div className="grid sm:grid-cols-3 gap-3">
                <TextInput label="Doctor's email" type="email" value={doctorEmail} onChange={(e) => setDoctorEmail(e.target.value)} placeholder="doctor@clinic.com" />
                <TextInput label="Doctor's name" value={doctorName} onChange={(e) => setDoctorName(e.target.value)} placeholder="Dr. Sharma" />
                <TextInput label="Clinic name (optional)" value={clinicName} onChange={(e) => setClinicName(e.target.value)} placeholder="City Health Clinic" />
              </div>
              <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', flexWrap: 'wrap' }}>
                <PrimaryButton onClick={sendEmail} disabled={emailSending || !doctorEmail.trim()}>
                  {emailSending ? <Loader2 className="w-4 h-4 animate-spin" /> : emailSent ? <CheckCircle className="w-4 h-4" /> : <Send className="w-4 h-4" />}
                  {emailSending ? 'Sending...' : emailSent ? 'Sent successfully' : 'Send to doctor'}
                </PrimaryButton>
                {emailSent && <span style={{ fontSize: '0.84rem', color: '#059669' }}>Health summary emailed to {doctorEmail}</span>}
                {emailError && <span style={{ fontSize: '0.84rem', color: '#dc2626' }}>Failed: {emailError}</span>}
              </div>
            </div>
          </SurfaceCard>

          <SurfaceCard title="Patient summary" icon={User}>
            <p style={{ fontSize: '0.92rem', lineHeight: 1.72, color: appTheme.espresso, whiteSpace: 'pre-wrap' }}>{brief.summary}</p>
          </SurfaceCard>

          <div className="grid md:grid-cols-2 gap-4">
            <SurfaceCard title="Key conditions" icon={Activity}>
              {brief.key_conditions.length ? (
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                  {brief.key_conditions.map((item, index) => <Badge key={`${item}-${index}`} tone="warning">{item}</Badge>)}
                </div>
              ) : (
                <div style={{ color: appTheme.espressoSoft, fontSize: '0.88rem' }}>No conditions recorded.</div>
              )}
            </SurfaceCard>

            <SurfaceCard title="Medications" icon={Pill}>
              {brief.medications.length ? (
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                  {brief.medications.map((item, index) => <Badge key={`${item}-${index}`} tone="violet">{item}</Badge>)}
                </div>
              ) : (
                <div style={{ color: appTheme.espressoSoft, fontSize: '0.88rem' }}>No medications recorded.</div>
              )}
            </SurfaceCard>
          </div>

          {brief.recent_concerns.length > 0 ? (
            <SurfaceCard title="Recent concerns" icon={Clock}>
              <div style={{ display: 'grid', gap: '0.6rem' }}>
                {brief.recent_concerns.map((item, index) => (
                  <div key={`${item}-${index}`} style={{ padding: '0.8rem 0.9rem', borderRadius: '0.9rem', background: '#faf8f5', borderLeft: `3px solid ${appTheme.copper}` }}>
                    <div style={{ fontSize: '0.88rem', lineHeight: 1.6, color: appTheme.espresso }}>{item}</div>
                  </div>
                ))}
              </div>
            </SurfaceCard>
          ) : null}

          {brief.uploaded_reports.length > 0 ? (
            <SurfaceCard title="Uploaded reports" icon={FileUp}>
              <div style={{ display: 'grid', gap: '0.7rem' }}>
                {brief.uploaded_reports.map((report, index) => (
                  <div key={`${report.report_name}-${index}`} style={{ padding: '0.95rem', borderRadius: '1rem', background: '#faf8f5', border: `1px solid ${appTheme.border}` }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', gap: '0.75rem', flexWrap: 'wrap' }}>
                      <div style={{ fontSize: '0.9rem', fontWeight: 700, color: appTheme.espresso }}>{report.report_name}</div>
                      {report.saved_at ? <div style={{ fontSize: '0.75rem', color: appTheme.espressoSoft }}>{new Date(report.saved_at).toLocaleDateString()}</div> : null}
                    </div>
                    {report.summary ? <div style={{ fontSize: '0.82rem', lineHeight: 1.6, color: appTheme.espressoSoft, marginTop: '0.35rem' }}>{report.summary}</div> : null}
                    <div style={{ display: 'flex', gap: '0.45rem', flexWrap: 'wrap', marginTop: '0.6rem' }}>
                      {report.medicines?.map((item, idx) => <Badge key={`m-${index}-${idx}`} tone="violet">{item}</Badge>)}
                      {report.conditions?.map((item, idx) => <Badge key={`c-${index}-${idx}`} tone="warning">{item}</Badge>)}
                    </div>
                  </div>
                ))}
              </div>
            </SurfaceCard>
          ) : null}

          <div style={{ fontSize: '0.78rem', textAlign: 'center', color: appTheme.espressoSoft }}>
            Generated {new Date(brief.generated_at).toLocaleString()} - for doctor reference only, not a diagnosis.
          </div>
        </div>
      ) : null}

      {!brief && !loading && !error ? (
        <div style={{ marginTop: '1rem' }}>
          <SurfaceCard>
            <EmptyState icon={Stethoscope} title="Ready to generate" subtitle="Enter a patient ID to create a doctor-facing brief using calls, reports, and stored memory." />
          </SurfaceCard>
        </div>
      ) : null}
    </AppPage>
  )
}
