services:
  - type: web
    name: aarogyavaani-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: VAPI_SECRET
        sync: false
      - key: SERVER_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.7
    healthCheckPath: /health
    plan: free
